### ISSUE TITLE
Pure black background

### ISSUE THREAD

**Issue by picorealm** [xdg/vim-darkluma#1]
Hi, thanks for creating this color scheme for Vim.  I really like it however I would like to change the background to pure black.  I'm looking at darkluma.vim but not entirely sure which line(s) to edit to change the background to pure black.

**Comment by xdg** [comment]
Hi.  I'm surprised you found it, but glad you're enjoying it.  If you just want to tweak normal text, you could change the ` hi Normal guifg=#cccccc guibg=#191919 guisp=NONE gui=NONE cterm=NONE` line `guilbg` color.  However, it might be more useful in the long-run to install the [vim-coloretemplate](https://github.com/lifepillar/vim-colortemplate) plugin and modify the [darkluma.colortemplate](https://github.com/xdg/vim-darkluma/blob/master/templates/darkluma.colortemplate) file, as it's more readable. Then run `:Colortemplate!` to compile to `colors/darkluma.vim`.

**Comment by picorealm** [comment]
Thanks for the info!  Yes I found darkluma on https://vimcolors.com/

**Comment by picorealm** [comment]
FYI I changed it by installing the vim-colortemplate plugin then changed this line:
     Normal               white             black90pct
under # Default highlight groups {{{   to:
     Normal               white             black

The command I used was :Colortemplates! ~/.vim
Without ~/.vim it saves the template to the git folder /colors directory, not ~/.vim/colors
